theme: jekyll-theme-minimal

title: Applied AI group @ Argonne National Laboratory
description: Supporting website for documentation of activities, including schedule of speaker series, recording of previous talks, documentation for tutorials, of the Applied AI group at Argonne National Laboratory
permalink: ':title/'
baseurl: "/" 
url: https://appliedai-anl.github.io/
