theme: minima

title: Applied AI group @ Argonne National Laboratory
author: Dennis Trujillo, Peco Myint, Arun Baskaran, Yanqi Luo, Anakha Babu, Jose L. Martinez-Marin, Rohit Batra, Qunfei Zhou 
description: Supporting website for documentation of activities, including schedule of speaker series, recording of previous talks, documentation for tutorials, of the Applied AI group at Argonne National Laboratory
  
logo: "/assets/imgs/argonne_logo.png"
# social links
twitter_username: # your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username: # your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
